apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-secure-app
  labels:
    app: my-secure-app
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-secure-app
  template:
    metadata:
      labels:
        app: my-secure-app
        environment: production
    spec:
      containers:
        - name: app
          image: nginx:1.25.3
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"